# Hyperparameters

prediction_horizon: 16
observation_horizon: 6
action_horizon: 8
batch_size: 2
num_workers: 4
learning_rate: 0.0001
weight_decay: 0.000001
num_warmup_steps: 1000
epochs: 100
num_diffusion_iters: 100


model_path: "models/uncork_v1"
dataset_path: "uncork_v1.zarr"

device: "cuda"
wandb_project: "real-bartender"
