# Hyperparameters
prediction_horizon: 16
observation_horizon: 2
action_horizon: 8
action_dim: 14
batch_size: 16
num_workers: 8
learning_rate: 0.0001
weight_decay: 0.000001
num_warmup_steps: 500
epochs: 100
num_diffusion_iters: 100

use_pretrained_model: True
model_path: "models/uncork_v2.pt"
dataset_path: "dataset/transformed_data/uncork_v2.zarr"

device: "cuda"
wandb_project: "real-bartender"a
run_name: "uncork_v2_8_workers"
