# Hyperparameters
prediction_horizon: 16
observation_horizon: 2
action_horizon: 8
batch_size: 48
num_workers: 8
learning_rate: 0.0001
weight_decay: 0.000001
num_warmup_steps: 500
epochs: 100
num_diffusion_iters: 100

use_pretrained_model: True
model_path: "models/uncork_v2.pt"
dataset_path: "dataset/uncork_v2.zarr"

device: "cuda"
wandb_project: "real-bartender"
run_name: ""
